services:
  photodrive-backend:
    build:
      context: ./core
      dockerfile: Dockerfile
    container_name: photodrive-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      DATASOURCE_PASSWORD: ${DATASOURCE_PASSWORD}
      DATASOURCE_URL: ${DATASOURCE_URL}
      DATASOURCE_USERNAME: ${DATASOURCE_USERNAME}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_USERNAME: ${MAIL_USERNAME}
      DIR: ${DIR}
      STORAGE_TEMP_PATH: ${STORAGE_TEMP_PATH}
      TOKEN_SECRETKEY: ${TOKEN_SECRETKEY}
      ORG_MAX_SIZE: ${ORG_MAX_SIZE}
      SWAGGER_USER: ${SWAGGER_USER}
      SWAGGER_PASSWORD: ${SWAGGER_PASSWORD}
      COOKIE_SECURE: ${COOKIE_SECURE:-false}
      SERVER_FORWARD_HEADERS_STRATEGY: framework
    volumes:
      - photodrive-data:/app/photodrive
      - photodrive-temp:/app/photodrive-temp
    networks:
      - photodrive-internal

  photodrive-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: photodrive-frontend
    restart: unless-stopped
    ports:
      - "3000:8080"
    depends_on:
      - photodrive-backend
    networks:
      - photodrive-internal

volumes:
  photodrive-data:
  photodrive-temp:

networks:
  photodrive-internal:
